CREATE SCHEMA CORE;

-- DROPS
DROP TABLE CORE.TB_USER IF EXISTS;

DROP SEQUENCE IF EXISTS CORE.SEQ_USER;

-- CREATE
CREATE SEQUENCE CORE.SEQ_USER INCREMENT BY 1 NO MINVALUE NO MAXVALUE START WITH 1;


CREATE TABLE CORE.TB_USER
(
    id_user     numeric(19, 0) NOT NULL,
    nm_nickname varchar(255)   NOT NULL UNIQUE,
    dt_create   datetime       NOT NULL,
    PRIMARY KEY (id_user)
);
